name: onfly_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.1
  dio: ^5.3.3
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.2
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
